### ISSUE TITLE
Videobridge Users error

### ISSUE THREAD

**Issue by altiport** [udima-university/ansible-jitsi-meet#1]
While installing, I get this error

TASK [jitsi-meet : Videobridge users] **********************************************************************************************************************************
fatal: [eclassroom.skouras-languages.gr]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'videobridge_user'\n\nThe error appears to be in '/ansible-jitsi-meet/roles/jitsi-meet/tasks/xmpp_users.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n## or use prosodyctl to check if users exist (will complicate looping...)\n- name: Videobridge users\n  ^ here\n"}

**Comment by inittab** [comment]
Hi, you have a host in the `[videobridges]` group (in the `hosts` file) but it is missing the `videobridge_user` variable in its `hosts_vars/HOSTNAME`. You will also need a `videobridge_pass` variable for it.
