### ISSUE TITLE
error for token setup

### ISSUE THREAD

**Issue by amg-web** [udima-university/ansible-jitsi-meet#12]
Ubuntu 18.04. Any ideas?

TASK [jitsi-meet : Build lua luajwtjitsi] *****************
fatal: [visio.wipnco.com]: FAILED! => {"changed": true, "cmd": ["luarocks", "install", "luajwtjitsi"], "delta": "0:00:04.515750", "end": "2021-04-21 15:22:11.176935", "msg": "non-zero return code", "rc": 1, "start": "2021-04-21 15:22:06.661185", "stderr": "Hunk 1 found at offset 2...\nsuccessfully patched src/openssl.c\nsrc/openssl.c:83:10: fatal error: lua.h: No such file or directory\n #include <lua.h>\n          ^~~~~~~\ncompilation terminated.\n\nError: Failed installing dependency: https://luarocks.org/luaossl-20200709-0.src.rock - Build error: Failed compiling object src/openssl.o", "stderr_lines": ["Hunk 1 found at offset 2...", "successfully patched src/openssl.c", "src/openssl.c:83:10: fatal error: lua.h: No such file or directory", " #include <lua.h>", "          ^~~~~~~", "compilation terminated.", "", "Error: Failed installing dependency: https://luarocks.org/luaossl-20200709-0.src.rock - Build error: Failed compiling object src/openssl.o"], "stdout": "Installing https://luarocks.org/luajwtjitsi-2.0-0.src.rock\nMissing dependencies for luajwtjitsi 2.0-0:\n   luaossl >= 20190731-0 (not installed)\n   lua-cjson == 2.1.0-1 (2.1devel-1 installed)\n   lbase64 >= 20120807-3 (not installed)\n\nluajwtjitsi 2.0-0 depends on luaossl >= 20190731-0 (not installed)\nInstalling https://luarocks.org/luaossl-20200709-0.src.rock\nApplying patch config.h.diff...\ngcc -O2 -fPIC -I/usr/include/lua5.1 -c src/openssl.c -o src/openssl.o -D_REENTRANT -D_THREAD_SAFE -DCOMPAT53_PREFIX=luaossl -D_GNU_SOURCE -I/usr/include -I/usr/include", "stdout_lines": ["Installing https://luarocks.org/luajwtjitsi-2.0-0.src.rock", "Missing dependencies for luajwtjitsi 2.0-0:", "   luaossl >= 20190731-0 (not installed)", "   lua-cjson == 2.1.0-1 (2.1devel-1 installed)", "   lbase64 >= 20120807-3 (not installed)", "", "luajwtjitsi 2.0-0 depends on luaossl >= 20190731-0 (not installed)", "Installing https://luarocks.org/luaossl-20200709-0.src.rock", "Applying patch config.h.diff...", "gcc -O2 -fPIC -I/usr/include/lua5.1 -c src/openssl.c -o src/openssl.o -D_REENTRANT -D_THREAD_SAFE -DCOMPAT53_PREFIX=luaossl -D_GNU_SOURCE -I/usr/include -I/usr/include"]}

**Comment by amg-web** [comment]
Ubuntu 20 with token 

everything pass
system is not working when try to connect I see message that something goes wrong.

**Comment by inittab** [comment]
Hi, the issue with Ubuntu 18 is beyond this project's scope (related to the lua command to install "luajwjitsi").
As to the issue with Ubuntu 20... nothing we can do without further information. Regards, Alberto
