### ISSUE TITLE
Is there a plan to support some kind of autoscaling?

### ISSUE THREAD

**Issue by renepardon** [udima-university/ansible-jitsi-meet#20]
Hello,

I like your playbook! Do you have an idea how one could implement autoscaling for JVB if you want to host more rooms and users at once?

**Comment by inittab** [comment]
Hi! Thanks for getting in touch. We (at Udima) are using Google Cloud for our Jitsi infrastructure and use a couple of shell/python scripts to start a new Jibri server when all the running instances are busy and shut them down when they stop streaming. It's a very ad-hoc solution (too ad-hoc to be published) but it works. I guess the same could be done with your video bridges.

**Comment by Oliver-ke** [comment]
Thanks, @inittab  for sharing, can you give more detail on how you autoscale JVB? I'm currently trying to do a similar setup

**Comment by inittab** [comment]
Hi, I haven't autoscaled JVB, just jibris. I guess it's a matter of having a JVB image that you can use to start new instances while monitoring the load on the active ones. I'm afraid I don't have the time to implement this soon.

**Comment by Oliver-ke** [comment]
> Hi, I haven't autoscaled JVB, just jibris. I guess it's a matter of having a JVB image that you can use to start new instances while monitoring the load on the active ones. I'm afraid I don't have the time to implement this soon.

Thank you. I'll try figure it out
