### ISSUE TITLE
Playbook not working any more for Debian 10?

### ISSUE THREAD

**Issue by oe79** [udima-university/ansible-jitsi-meet#21]
Hello,
one year ago I installed Jitsi with this playbook and it worked like a charm on Debian 10. But now with the newer Jitsi versions Jitsi is not working any more. The playbook installs everything without errors.. But when i call jitsi in the browser, it tries to start but shows the error "something went wrong ..."
I think, that the jitsi-token-modul causes the problems. I installed a normal Jitsi on my own, which worked fine, but after installing token-module also crashed.

I can use an older playbook and manually edit it to use
- jitsi-meet-web=1.0.4628-1
- jitsi-meet=2.0.5390-3
- jitsi-videobridge2=2.1-416-g2f43d1b4-1
- jitsi-meet-web-config=1.0.4628-1
- jitsi-meet-tokens=1.0.4628-1
- jitsi-meet-prosody=1.0.4628-1
- jigasi=1.1-166-g929a439-1
- jicofo=1.0-692-hf-1

But this is no solution because Chrome doesn't support this old versions correct anymore.

I use a clean Debian 10 VM on Hetzner cloud.

Thanks for helping. 
Oe

**Comment by inittab** [comment]
Hi, the playbook does not install jitsi-meet-tokens. I don't know what modifications that package does to the resulting install but it shouldn't be required when using this playbook.

**Comment by oe79** [comment]
Hi, but how is token based authentication working as described under "User authentication support"?
The other thing is: why jitsi does not work anymore out of the box when using the playbook and doing a fresh install? Perhaps s.o. can test it an do a fresh install using the playbook.

**Comment by inittab** [comment]
The jitsi-meet-tokens package does not install anything, it simply modifies configuration files. That's the same thing the ansible playbook does. So if you install it (jitsi-meet-tokens) you may break the playbook's work. Logs may be helpful in order to debug your installation not working.

**Comment by oe79** [comment]
I didn't install  the token-plugin when i used the playbook. I only installed it, when installing jitsi on my own.

Well, as i told you: the playbook runs through without errors, but then jitsi is not working. in older installations it worked fine.
It would be nice to know, if the playbook only does not work for me, or if it perhaps is a common problem when installing on a fresh actual debian 10.
For logs I have to create a new VM and let do ansible the job. If you're interested, you can try it yourself on the Test-VM and I give you access to it.

**Comment by inittab** [comment]
Thanks for the offer. I'll try to set up a new VM to test it and get back to you as time permits.

**Comment by oe79** [comment]
Thank you very much!

**Comment by oe79** [comment]
Hello inittab,
did you already have the time to test it?
Thanks for your answer.

**Comment by inittab** [comment]
Hi, I'm sorry I didn't have the time. I'll try to look at it this week, hopefully tomorrow, and get back to you. Sorry again.

**Comment by inittab** [comment]
Hi, I'm very sorry this took so long. I think the issue was the jicofo user was not created in prosody. My last commit fixes that. Please let me know if that fixes it for you. Else, please send me as much logs as possible after the playbook is run. Thanks, Alberto

**Comment by oe79** [comment]
Hi, thanks for trying to help, but it still doesn't work. I get an "Unfortunately something went wrong" error when opening a meeting.
These are the logs for prosody, jicofo and videobridge after running the playbook:

[prosody.txt](https://github.com/udima-university/ansible-jitsi-meet/files/8749340/prosody.txt)
[jicofo.txt](https://github.com/udima-university/ansible-jitsi-meet/files/8749341/jicofo.txt)
[jvb.txt](https://github.com/udima-university/ansible-jitsi-meet/files/8749342/jvb.txt)

Let me know, if you need other logs.
Thanks
Oe

**Comment by inittab** [comment]
Hi, from the jicofo logs, the problem seems to be the one fixed in my commit (Jicofo not authenticating itself in prosody). 

Did you try the playbook on a new deployment or on one already deployed?

Can you check the password value in the "client" section of /etc/jitsi/jicofo/jicofo.conf matches with the one in /var/lib/prosody/auth.YOURDOMAIN/focus.dat.

If you check your jicofo and prosody logs, you can see that jicofo first connects OK:
Prodody:
May 22 11:37:23 c2s5615c6a2f660 info    Authenticated as focus@auth.meet.oeweb.de
Jicofo:
Jicofo 2022-05-22 11:37:23.119 INFO: [15] [xmpp_connection=client] XmppProviderImpl.doConnect#209: Connected, JID=null
But after that prosody restarts and it breaks.
Same thing happens with jvb authentication. Could you sendme (privately) /etc/prosody/conf.d/meet.oeweb.de.cfg.lua with all passwords ommited?

Thanks, Alberto

**Comment by oe79** [comment]
Hi,
I did it on a fresh installed Debian 10.
There is no "/var/lib/prosody/auth.YOURDOMAIN/focus.dat". I only can find a focus.dat in /var/lib/prosody/auth.YOURDOMAIN/accounts and /var/lib/prosody/auth.YOURDOMAIN/roster.
But there are no password values in it.
How can I send you privatly a message? Github does not support private messages.

Thanks again
Oe

**Comment by inittab** [comment]
Sorry, I meant /var/lib/prosody/auth.YOURDOMAIN/accounts/focus.dat, yes. Does that file contain:
return {
        ["password"] = "FOCUSPASSWORD";
};
At the bottom of inittab.org you may find my email address. agi@
