### ISSUE TITLE
Failed while running initial playbook

### ISSUE THREAD

**Issue by pmatos** [udima-university/ansible-jitsi-meet#8]
I have followed the simple setup of jitsi meet in a single server and got the following error:

```
TASK [jitsi-meet : Videobridge users] ********************************************************************************************************************
fatal: [***]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'videobridge_user'\n\nThe error appears to be in '/home/pmatos/dev/ansible-jitsi-meet/roles/jitsi-meet/tasks/xmpp_users.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n## or use prosodyctl to check if users exist (will complicate looping...)\n- name: Videobridge users\n  ^ here\n"}
```

**Comment by inittab** [comment]
Hi, as the error message reads, it seems that you are missing the "videobridge_user" variable in the host_vars for your server.

**Comment by pmatos** [comment]
But I am not, in `host_vars/foo.domain.com/main.yml` I have:
```
videobridge_user: "foo.domain.com"
```

**Comment by inittab** [comment]
That's weird... And you have something like in hosts file?:
[videobridges]
foo.domain.com

**Comment by pmatos** [comment]
I think the problem was leaving `central_host` in `[videobridges]`. After removing it, everything works.

**Comment by pmatos** [comment]
Shouldn't the `hosts` file just contain for the videobridges section:
```
## videbridge: jitsi-videobridge2
[videobridges]
jvb.YOURDOMAIN.TLD
```

instead of:
```
## videbridge: jitsi-videobridge2
[videobridges]
central_host
jvb.YOURDOMAIN.TLD
```

**Comment by inittab** [comment]
Hi, it all depends on your setup. The "[videobridges]" section should include those hosts acting as videobridges. If "central_host" is going to act as such, it should be listed there. Otherwise, it shouldn't.
You may run the whole stack in one host, which will be in "[central]" AND "[videobridges]".  Or leave a host for prosody/jicofo and the rest for videobridges. In this case the former host won't be in "[videobridges]".
